
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /


## HAZEM
vente_front:
    resource: "@GestionVenteBundle/Resources/config/routing-front.yml"
    prefix: /vente

vente_back:
    resource: "@GestionVenteBundle/Resources/config/routing-back.yml"
    prefix: /admin/vente


gestion_stock:
    resource: "@GestionStockBundle/Resources/config/routing.yml"
    prefix:   /

livraison:
    resource: "@LivraisonBundle/Resources/config/routing.yml"
    prefix:   /

gestion_achat:
    resource: "@GestionAchatBundle/Resources/config/routing.yml"
    prefix:   /


tool:
    resource: "@ToolBundle/Resources/config/routing.yml"
    prefix:   /tool

#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

toiba_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yaml"

