

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


vente_front:
    resource: "@GestionVenteBundle/Resources/config/routing-front.yml"
    prefix: /vente

vente_back:
    resource: "@GestionVenteBundle/Resources/config/routing-back.yml"
    prefix: /admin/vente


tool:
    resource: "@ToolBundle/Resources/config/routing.yml"
    prefix:   /tool


#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

