app:
    resource: "@AppBundle/Controller/"
    type:     annotation


administration:
    resource: "@GestionVenteBundle/Resources/config/routing.yml"
    prefix: /administration/vente


#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

